/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as DashboardDashRouteImport } from './routes/dashboard/_dash'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as DashboardDashIndexRouteImport } from './routes/dashboard/_dash.index'
import { Route as DashboardDashUsersRouteImport } from './routes/dashboard/_dash.users'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashRoute = DashboardDashRouteImport.update({
  id: '/dashboard/_dash',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const DashboardDashIndexRoute = DashboardDashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDashRoute,
} as any)
const DashboardDashUsersRoute = DashboardDashUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardDashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cart': typeof AppCartRoute
  '/dashboard': typeof DashboardDashRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/dashboard/users': typeof DashboardDashUsersRoute
  '/dashboard/': typeof DashboardDashIndexRoute
}
export interface FileRoutesByTo {
  '/cart': typeof AppCartRoute
  '/products/$id': typeof ProductsIdRoute
  '/': typeof AppIndexRoute
  '/dashboard/users': typeof DashboardDashUsersRoute
  '/dashboard': typeof DashboardDashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/cart': typeof AppCartRoute
  '/dashboard/_dash': typeof DashboardDashRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/_app/': typeof AppIndexRoute
  '/dashboard/_dash/users': typeof DashboardDashUsersRoute
  '/dashboard/_dash/': typeof DashboardDashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/dashboard'
    | '/products/$id'
    | '/dashboard/users'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/cart' | '/products/$id' | '/' | '/dashboard/users' | '/dashboard'
  id:
    | '__root__'
    | '/_app'
    | '/_app/cart'
    | '/dashboard/_dash'
    | '/products/$id'
    | '/_app/'
    | '/dashboard/_dash/users'
    | '/dashboard/_dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DashboardDashRoute: typeof DashboardDashRouteWithChildren
  ProductsIdRoute: typeof ProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dash': {
      id: '/dashboard/_dash'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/_dash/': {
      id: '/dashboard/_dash/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashIndexRouteImport
      parentRoute: typeof DashboardDashRoute
    }
    '/dashboard/_dash/users': {
      id: '/dashboard/_dash/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardDashUsersRouteImport
      parentRoute: typeof DashboardDashRoute
    }
  }
}

interface AppRouteChildren {
  AppCartRoute: typeof AppCartRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartRoute: AppCartRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DashboardDashRouteChildren {
  DashboardDashUsersRoute: typeof DashboardDashUsersRoute
  DashboardDashIndexRoute: typeof DashboardDashIndexRoute
}

const DashboardDashRouteChildren: DashboardDashRouteChildren = {
  DashboardDashUsersRoute: DashboardDashUsersRoute,
  DashboardDashIndexRoute: DashboardDashIndexRoute,
}

const DashboardDashRouteWithChildren = DashboardDashRoute._addFileChildren(
  DashboardDashRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DashboardDashRoute: DashboardDashRouteWithChildren,
  ProductsIdRoute: ProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
